name: Run Tests
on: [push]
jobs:
    RunUnitTests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Install pytest and mocker
              run: pip install pytest pytest-spec pytest-describe mocker
            - name: Run pytest
              run: pyteset --spec --color=yes test_brute.py
    RunFunctionalTests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Install chromedriver
              uses: nanasess/setup-chromedriver@master
            - name: Install behave
              uses: pip install behave behave-webdriver
            - name: Run behave
              run: behave